### ISSUE TITLE
Add count(needs) to list of Locations

### ISSUE THREAD

**Issue by borazslo** [Koeroesi86/help.koro.si#7]
A különféle locations listáknál szerintem hasznos lenne ha ott lenne, hogy hányféle needs van ott. Mondjuk akkor ha több mint nulla. Így könnyebb látni, hogy melyik gyűjtőpontra érdemes kattintani és látni, hogy mire van szüksége.

**Comment by Koeroesi86** [comment]
Thanks for the feedback, will add count of needs to each location in listings.

**Comment by Koeroesi86** [comment]
Added counter, see on ex. https://help.koro.si/#/organisations/6b70e880-0265-47e3-8c8d-a444f69bf7e6
