### ISSUE TITLE
Add count(locations) to the fulllist of needs

### ISSUE THREAD

**Issue by borazslo** [Koeroesi86/help.koro.si#8]
A nagy needs listában, ahol minden ott van, lehetne a location link helyett location**s** link és egy szám, hogy hány location érintett. (Vagy ez így van, csak mindegyikhez egyetlen egy kell?)

**Comment by Koeroesi86** [comment]
Each need is unique per location at the moment (free text input). No grouping available yet, so hard to tell how many locations would need the same. I'm not even sure if that would be relevant information, however putting those locations on a map could be of some help?

**Comment by Koeroesi86** [comment]
Added a map if locations of needed donations have geolocation assigned. See on: https://help.koro.si/needs
Could this solve the issue?

**Comment by borazslo** [comment]
combined with the search field it is fine now. thanks.
